# Generated by Django 6.0.7 on 2026-07-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم المهنة/القسم (عربي)')),
                ('name_en', models.CharField(max_length=100, verbose_name='اسم المهنة/القسم (إنجليزي)')),
                ('section_type', models.CharField(choices=[('freelance', 'خدمات مهنية وصيانة (سباك، نجار، مبرمج...)'), ('delivery', 'طلبات وتوصيل (أكل، تاكسي، مشاوير...)')], max_length=20, verbose_name='القسم الرئيسي العام')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category', verbose_name='المهنة / التخصص'),
        ),
    ]
