# Generated by Django 6.0.7 on 2026-07-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section_type',
            field=models.CharField(choices=[('freelance', 'خدمات مهنية وصيانة (سباك، نجار، مبرمج...)'), ('delivery', 'طلبات وتوصيل (أكل، تاكسي، مشاوير...)'), ('marketplace', 'بيع وشراء (عقارات، سلع، منتجات)')], max_length=20, verbose_name='القسم الرئيسي العام'),
        ),
    ]
