# Generated by Django 6.0.7 on 2026-07-12 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_category_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='ماذا يدور في ذهنك؟')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts_images/', verbose_name='صورة المنشور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category', verbose_name='قسم الاهتمام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='كاتب المنشور')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
