# Generated by Django 6.0.7 on 2026-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_user.png', null=True, upload_to='profile_pics/', verbose_name='صورة الحساب'),
        ),
    ]
