# Generated by Django 6.0.7 on 2026-07-13 20:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_postaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'القسم والتخصص', 'verbose_name_plural': 'الأقسام والتخصصات'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='section_type',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='icon_emoji',
            field=models.CharField(default='🛠️', max_length=10, verbose_name='أيقونة التخصص (إيموجي)'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.category', verbose_name='القسم الأب (اتركه فارغاً ليكون قسماً رئيسياً)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='اسم القسم/التخصص بالعربية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم القسم/التخصص بالإنجليزية'),
        ),
    ]
