# Generated by Django 6.0.7 on 2026-07-13 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_category_options_remove_category_section_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='accounts.category', verbose_name='الاهتمامات والاحتياجات (لطالبي الخدمة فقط)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='accounts.category', verbose_name='التخصص المهني الرئيسي (للفنيين فقط)'),
        ),
    ]
