# Generated by Django 6.0.7 on 2026-07-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_interests_alter_user_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'الالقسم والتخصص', 'verbose_name_plural': 'الأقسام والتخصصات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_emoji',
            field=models.CharField(choices=[('🛠️', '🛠️ صيانة عامة / فني'), ('⚡', '⚡ كهرباء / فني كهربائي'), ('🪚', '🪚 نجارة / فني أثاث'), ('🚰', '🚰 سباكة / فني صحي'), ('🧱', '🧱 بناء ومعمار / مقاولات'), ('🎨', '🎨 نقاشة ودهانات / ديكور'), ('❄️', '❄️ تكييف وتبريد / صيانة أجهزة'), ('🧼', '🧼 خدمات تنظيف وغسيل'), ('🚗', '🚗 ميكانيكا وصيانة سيارات'), ('🚚', '🚚 نقل عفش وشحن بضائع'), ('🛵', '🛵 توصيل ودليفري سريع'), ('💻', '💻 صيانة كمبيوتر وهواتف'), ('👨\u200d🏫', '👨\u200d🏫 تدريس خصوصي / كورسات'), ('📝', '📝 كتابة وترجمة / خدمات مكتبية'), ('🩺', '🩺 رعاية صحية / تمريض منزلي'), ('✂️', '✂️ حلاقة وتجميل / صالونات'), ('🥦', '🥦 خضروات ومستلزمات منزلية'), ('🐾', '🐾 رعاية حيوانات أليفة'), ('🏢', '🏢 خدمات عقارية وعقود'), ('📦', '📦 خدمات أخرى متنوعة')], default='🛠️', max_length=10, verbose_name='أيقونة التخصص (إيموجي)'),
        ),
    ]
