# Generated by Django 6.0.7 on 2026-07-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_post_video_alter_category_icon_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_now',
            field=models.BooleanField(default=False, verbose_name='متاح الآن للعمل'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث للموقع'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض GPS'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول GPS'),
        ),
    ]
