# Generated by Django 6.0.7 on 2026-07-16 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_is_active_now_user_last_location_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100, unique=True, verbose_name='معرف غرفة الاتصال المشفر')),
                ('status', models.CharField(choices=[('ringing', 'جاري الرنين 📞'), ('active', 'مكالمة نشطة 🗣️'), ('ended', 'انتهت المكالمة ❌'), ('rejected', 'مرفوضة 🚫')], default='ringing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_calls', to=settings.AUTH_USER_MODEL, verbose_name='المتصل')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_calls', to=settings.AUTH_USER_MODEL, verbose_name='المستقبل')),
            ],
        ),
    ]
